--------------------------------------------------------------
-- ERROR_LOG TABLE
--------------------------------------------------------------

CREATE TABLE ERROR_LOG (
    ERROR_ID        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    STAGING_ID      NUMBER,                     -- MERGED_ALL.ID
    SOURCE_SYSTEM   VARCHAR2(50),               -- PRCS / CRIME_LEEDS / PS_WALES
    ERROR_TIME      DATE DEFAULT SYSDATE,
    ERROR_MESSAGE   VARCHAR2(4000),             -- Description of the issue
    RAW_DATA        VARCHAR2(4000)              -- Entire row as text/JSON
);
/

--------------------------------------------------------------
-- PROCESS_LOG TABLE
--------------------------------------------------------------

CREATE TABLE PROCESS_LOG (
    PROCESS_ID      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    START_TIME      DATE DEFAULT SYSDATE,
    END_TIME        DATE,
    STATUS          VARCHAR2(20),          -- SUCCESS / FAILED
    GOOD_COUNT      NUMBER,
    BAD_COUNT       NUMBER,
    REMARKS         VARCHAR2(4000)
);
